# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r-gnzp-0lLnZHaRV60kxCgAfu9AL9BDs
"""

#Q1)
 #def username(name,department):
   # """user print name and department """
   # return (f"Your name is {name} and Your departmant{department}")
#name=input("enter your name")
#department=input("enter your depatmant")
#user=username(name,department)
#print(user)
# print("#"*10)
#Q2)

# def sum(number1,number2):
#     """sum number1 and number2"""
#     return number1+number2
# def multiply(number1,number2):
#     """multiply number1 and number2"""
#     return number1*number2
# def minus(number1,number2):
#     """minus number1 and number2)"""
#     return number1-number2
# def divide(number1,number2):
#     """divide number1 and  number2)"""
#     return number1/number2
# num=sum(1,2)
# div=divide(10,2)
# mult=multiply(2,3)
# min=minus(8,3)
# print(num)
# print(div)
# print(mult)
# print(min)

#Q3)
# def check_number(num):
#   """check number is odd or even"""
#   if number %2!=0:
#     print(f"The number is odd = {number} ")
#   if number %2==0:
#     print(f"The number is even = {number} ")
# number=eval(input("Pleace, enter this number >== "))
# check_number(number)

#Q4)
# def first_name(fname):
#   """write your first name"""
#   print(f"my first name is {fname}")
# def last_name(lname):
#   """write your last name"""
#   print(f"my last name is {lname}")
# def my_age(age):
#   """write your age"""
#   print(f"my age is {age}")
# def favourite_subject(fsubject):
#   """write your favourite subject"""
#   print(f"my name is{fsubject}")
# fname=input("Pleace,enter your first name ")
# lname=input("Pleace, enter your name ")
# age=eval(input("Pleace,enter your age   "))
# fsubject=input("Pleace, your favourit subject")
# first_name(fname)
# last_name(lname)
# my_age(age)
# favourite_subject(fsubject)
# print(f"my name is {fname }{lname}, my age is {age} and my favourite subject {fsubject}" )

#Q5)
# def swap_number (number1,number2):
#    """swap the number """
#   number1 , number2 =number2 , number1
#   print(f"After the swap is {number1 , number2 }")
# num1=eval(input("Pleace , enter number  "))
# num2=eval(input("Pleace , enter number  "))
# print(f"Before the swap is ({num1},{num2}) ")
# swap=swap_number(num1,num2)

#Q6)
# def gpa(mark):
#    """ write mark convert gpa"""
#   if 100>=mark and mark >=95:
#     print(f"grade is 'A+' mark is {mark} , good job")
#   if mark <95 and mark >=90 :
#     print(f"grade is 'A' mark is {mark} , good job ")
#   elif mark <90 and mark >=85:
#     print(f"grade is 'B+' mark is {mark} , good job")
#   elif mark <85 and mark >=82:
#     print(f"grade is 'B' mark is {mark} , good job")
#   elif mark <82 and mark >=75:
#     print(f"grade is 'C+' mark is {mark} , good job")
#   elif mark <75 and mark >=60:
#     print(f"grade is 'C' mark is {mark} , good job")
#   elif mark <60 and mark >=50:
#     print(f"grade is 'D' mark is {mark} , good job")
#   elif mark <50 :
#     print(f"grade is 'f' mark is {mark} , hard luck ")
# mark=eval(input("Pleace , enter your mark >== "))
# gpa(mark) 

#Q7)
# Winter =["December","January","February","12","1","2"] 
# Spring =["March","April","May","3","4","5"]
# Summer=["Agust","July","June","6","7","8"]
# Autumn =["November","October","September","11","10","9"]
# def Seasons(Month):
#   """Pleace write your month"""
#   if Month in Winter:
#     print (f"We are in the winter season in month  {Month} ")
#   elif Month in Spring:
#     print (f"We are in the spring  season in month  {Month} ")
#   elif Month in Summer:
#     print (f"We are in the Summer season in month  {Month} ")
#   elif Month in Autumn :
#     print (f"We are in the Autumn season in month  {Month} ")
#   else:
#     print("Erorr")
# Month=input("Pleace , enter month  ").capitalize()
# Seasons(Month)
#Q8)
# def Type_variabl(Var):
#   """write type variabl"""
#   if type(Var) is str:
#     print (f"The type variabl is 'string ' {type(Var)} ")
#   elif type(Var) is int:
#     print (f"The type variabl is  'integer number' {type(Var)} ")
#   elif type(Var) is float:
#     print (f"The type variabl is  'float number' {type(Var)} ")
#   else:
#     print(type(Var))
# Type_variabl("ziad elsaid khaliefa")